name: Build for release
on:
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Set permissions
        run: chmod +x gradlew

      - name: Temporary workaround
        run: ./gradlew --no-daemon Common:build
        env:
          GITHUB_VERSION: ${{ github.event.release.tag_name }}

      - name: Build artifacts
        run: ./gradlew --no-daemon Mod:packJar
        env:
          GITHUB_VERSION: ${{ github.event.release.tag_name }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Mod/build/libs/ModLib.jar
          asset_name: ModLib.jar
          asset_content_type: application/zip
